AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    # simple_formにより自動生成されるファイル
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

require:
  - rubocop-rails

# 1行あたりの文字数
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A( *)#']

# ブロックあたりの行数
Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'

# ネストしたモジュールとクラスの定義スタイル
Style/ClassAndModuleChildren:
  Enabled: false

# トップレベルのドキュメント
Style/Documentation:
  Enabled: false
