AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

# ネストしたモジュールとクラスの定義スタイル
Style/ClassAndModuleChildren:
  Enabled: false

# トップレベルのドキュメント
Style/Documentation:
  Enabled: false
