AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

require:
  - rubocop-rails

# 1行あたりの文字数
Layout/LineLength:
  IgnoredPatterns: ['\A( *)#']

# ネストしたモジュールとクラスの定義スタイル
Style/ClassAndModuleChildren:
  Enabled: false

# トップレベルのドキュメント
Style/Documentation:
  Enabled: false
