version: '3'
services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
  rpweb:
    container_name: rpweb
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - cache:/cache
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@db
      SPROCKETS_CACHE: /cache
    depends_on:
      - db
volumes:
  cache:
