name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start service.
        run: docker-compose up -d
      - name: Run RuboCop.
        run: docker-compose exec -T rpweb rubocop
      - name: Create Database.
        run: docker-compose exec -T rpweb rails db:create RAILS_ENV=test
      - name: Run yarn install.
        run: docker-compose exec -T rpweb yarn install
      - name: Run Minitest.
        run: docker-compose exec -T rpweb rails test
      - name: Upload reports to Codecov.
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
